gitSourceBranch = "main"

[docusaurus]
url = "https://qscythee.github.io"
baseUrl = "/ModuleForge"

[[classOrder]]
classes = ["Nexus"]

[[classOrder]]
classes = ["FlagManager"]

[[classOrder]]
classes = ["Serializer"]
